# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: IntegracionContinuaPrueba

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Permiso de ejecucion gradlew
      run: chmod +x gradlew
    - name: Prueba gradle
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew build
