# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ desarrollo ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Configurar JDK para construir el proyecto de Android
      - name: Set-Up JDK #El nombre que tu elijas
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      # Permite ejecutar ./gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      # Ejecuta prueba de construcción de app Android
      - name: Run-Lint
        run: ./gradlew lint
      
      - name: upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint_html_report
          path: app/build/reports/lint-results.html
     
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      # Permite ejecutar ./gradlew
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test
      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: unit_test_report
          path: app/build/reports/test-results.html      
    
        
        
        
        
        
        
        
        
        
